### ISSUE TITLE
Stack trace  SSL_free crash

### ISSUE THREAD

**Issue by ckaminski** [ckaminski/hunter-example#1]
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./foo...(no debugging symbols found)...done.
(gdb) r localhost 3000 6 server.key server.cert
Starting program: /home/ckaminski/tmp/hunter-test/build/foo localhost 3000 6 server.key server.cert
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5b9a700 (LWP 16324)]
[New Thread 0x7ffff5399700 (LWP 16325)]
[New Thread 0x7ffff4b98700 (LWP 16326)]
[New Thread 0x7ffff4397700 (LWP 16327)]
[New Thread 0x7ffff3b96700 (LWP 16328)]
[New Thread 0x7ffff3395700 (LWP 16329)]

Thread 4 "foo" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4b98700 (LWP 16326)]
__GI___libc_free (mem=0x4) at malloc.c:2951
2951	malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x4) at malloc.c:2951
#1  0x00000000004d2998 in BIO_free ()
#2  0x00000000004d3404 in BIO_free_all ()
#3  0x000000000049b35c in SSL_free ()
#4  0x00007ffff7988ee8 in std::_Sp_counted_ptr_inplace<nghttp2::asio_http2::server::connection<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >, std::allocator<nghttp2::asio_http2::server::connection<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
   from /home/ckaminski/.hunter/_Base/c4a9619/e1266bb/0303cbf/Install/lib/libnghttp2_asio.so.1
#5  0x00000000004814da in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#6  0x00007ffff79893cc in boost::asio::detail::wait_handler<std::_Bind<std::_Mem_fn<void (nghttp2::asio_http2::server::connection<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > >::*)()> (std::shared_ptr<nghttp2::asio_http2::server::connection<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > > > >)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
   from /home/ckaminski/.hunter/_Base/c4a9619/e1266bb/0303cbf/Install/lib/libnghttp2_asio.so.1
#7  0x00007ffff797b705 in boost::asio::io_service::run() ()
   from /home/ckaminski/.hunter/_Base/c4a9619/e1266bb/0303cbf/Install/lib/libnghttp2_asio.so.1
#8  0x00007ffff7975e9d in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, std::_Bind_simple<std::_Mem_fn<unsigned long (boost::asio::io_service::*)()> (std::shared_ptr<boost::asio::io_service>)>, unsigned long> >::_M_invoke(std::_Any_data const&) () from /home/ckaminski/.hunter/_Base/c4a9619/e1266bb/0303cbf/Install/lib/libnghttp2_asio.so.1
#9  0x00007ffff7975fc9 in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) ()
   from /home/ckaminski/.hunter/_Base/c4a9619/e1266bb/0303cbf/Install/lib/libnghttp2_asio.so.1
#10 0x00007ffff7708a99 in __pthread_once_slow (once_control=0x9436c8, 
    init_routine=0x7ffff722bac0 <__once_proxy>) at pthread_once.c:116
#11 0x00007ffff7977f1d in std::thread::_Impl<std::_Bind_simple<std::__future_base::_Async_state_impl<std::_Bind_simple<std::_Mem_fn<unsigned long (boost::asio::io_service::*)()> (std::shared_ptr<boost::asio::io_service>)>, unsigned long>::_Async_state_impl(std::_Bind_simple<std::_Mem_fn<unsigned long (boost::asio::io_service::*)()> (std::shared_ptr<boost::asio::io_service>)>&&)::{lambda()#1} ()> >::_M_run() ()
   from /home/ckaminski/.hunter/_Base/c4a9619/e1266bb/0303cbf/Install/lib/libnghttp2_asio.so.1
#12 0x00007ffff722cc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff77016ba in start_thread (arg=0x7ffff4b98700) at pthread_create.c:333
---Type <return> to continue, or q <return> to quit---Quit
(gdb) Quit
(gdb) Quit
(gdb) quite
Undefined command: "quite".  Try "help".
(gdb) quit
A debugging session is active.

	Inferior 1 [process 16320] will be killed.

Quit anyway? (y or n) y

**Comment by ckaminski** [comment]
I believe this issue was related to different OpenSSL linkages between OpenSSL (dynamic) and the example program (static).   Updated project and build to correct.  The end goal was to provide a useful working project example for Hunter.
